In [241]:
import numpy as np

Questão 1.1

In [242]:
w1 = 1
w2 = 1
w3 = 1
w4 = 1

In [243]:
def ytil1 (x1, x2):
    y = w1*np.exp(-1*w2*(x1**2)) + w3*np.log(x2+1)
    return y

In [244]:
def ytil2 (x1, x2):
    y = w3*(x1**2) + w4 + 0*x2
    return y

In [245]:
lotes_entradas = np.array([(0,0),(1,1),(0, 1), (1,0)])
lotes_saidas = np.array([(0,1), (0.83, 2.2), (0.83, 1), (0,2.2)])
lotes_entradas
lotes_saidas

array([[0.  , 1.  ],
       [0.83, 2.2 ],
       [0.83, 1.  ],
       [0.  , 2.2 ]])

Rodando as entradas

In [246]:
saidas = [None] * len(lotes_entradas)
for i in range(len(lotes_entradas)):
    saidas[i] = [ytil1(lotes_entradas[i][0],lotes_entradas[i][1]), ytil2(lotes_entradas[i][0],lotes_entradas[i][1])]
    print(saidas[i])


[np.float64(1.0), np.int64(1)]
[np.float64(1.0610266217313877), np.int64(2)]
[np.float64(1.6931471805599454), np.int64(1)]
[np.float64(0.36787944117144233), np.int64(2)]


Calculando as diferenças

In [247]:
erro = saidas - lotes_saidas
erro

array([[ 1.        ,  0.        ],
       [ 0.23102662, -0.2       ],
       [ 0.86314718,  0.        ],
       [ 0.36787944, -0.2       ]])

Calculado F(w)

In [248]:
fw = np.array([None] * len(erro))
for i in range(len(fw)):
    fw[i] = 2*(erro[i]/(lotes_saidas[i][0] + 1))**2 + 7*(erro[i])**2
    print(fw[i])
media_fw = np.mean(fw)
media_fw

[9. 0.]
[0.40548822 0.30388844]
[5.66009737 0.        ]
[1.21801755 0.36      ]


array([4.07090079, 0.16597211])

In [249]:
def deltaw1(A):
    y = (-4*(erro[A][0]/((lotes_saidas[A][0] +1)**2))*np.exp(-w2*(lotes_entradas[A][0])**2))/2
    return y

In [250]:
def deltaw2(A):
    y = (-4*(erro[A][0]/((lotes_saidas[A][0] +1)**2))*w1*np.exp(-w2*((lotes_entradas[A][1])**2))*(-(lotes_entradas[A][1])**2))/2
    return y

In [251]:
def deltaw3(A): 
    y = (-4*(erro[A][0]/((lotes_saidas[A][0] +1)**2))*np.log(lotes_entradas[A][1]+1) + -14*(erro[A][1])*((lotes_entradas[A][1])**2))/2
    return y

In [252]:
def deltaw4(A): 
    y = -14*(erro[A][1])/2
    return y

Calculando  todos os Novos w

In [253]:
A = 3
alfa = 0.1
w1novo = w1 + alfa*deltaw1(A)
w2novo = w2 + alfa*deltaw2(A)
w3novo = w3 + alfa*deltaw3(A)
w4novo = w4 + alfa*deltaw4(A)
print(w1novo)
print(w2novo)
print(w3novo)
print(w4novo)

0.9729329433526774
1.0
1.0
1.1400000000000001


In [254]:
w1 = w1novo
w2 = w2novo
w3 = w3novo
w4 = w4novo
print(w1)
print(w2)
print(w3)
print(w4)

0.9729329433526774
1.0
1.0
1.1400000000000001


Atualizando

In [255]:
print(w1)
print(w2)
print(w3)
print(w4)


0.9729329433526774
1.0
1.0
1.1400000000000001


In [256]:
saidas = [None] * len(lotes_entradas)
for i in range(len(lotes_entradas)):
    saidas[i] = [ytil1(lotes_entradas[i][0],lotes_entradas[i][1]), ytil2(lotes_entradas[i][0],lotes_entradas[i][1])]
    print(saidas[i])

[np.float64(0.9729329433526774), np.float64(1.1400000000000001)]
[np.float64(1.0510692080578148), np.float64(2.14)]
[np.float64(1.6660801239126228), np.float64(1.1400000000000001)]
[np.float64(0.35792202749786955), np.float64(2.14)]


In [257]:
erro = saidas - lotes_saidas
erro

array([[ 0.97293294,  0.14      ],
       [ 0.22106921, -0.06      ],
       [ 0.83608012,  0.14      ],
       [ 0.35792203, -0.06      ]])

In [258]:
fw = np.array([None] * len(erro))
for i in range(len(fw)):
    fw[i] = 2*(erro[i]/(lotes_saidas[i][0] + 1))**2 + 7*(erro[i])**2
    print(fw[i])
media_fw = np.mean(fw)
media_fw

[8.51938661 0.1764    ]
[0.37128782 0.02734996]
[5.31067822 0.14890534]
[1.1529736 0.0324   ]


array([3.83858156, 0.09626382])

In [259]:
A = 3
alfa = 0.2
w1novo = w1 + alfa*deltaw1(A)
w2novo = w2 + alfa*deltaw2(A)
w3novo = w3 + alfa*deltaw3(A)
w4novo = w4 + alfa*deltaw4(A)
print(w1novo)
print(w2novo)
print(w3novo)
print(w4novo)

0.920264081169131
1.0
1.0
1.2240000000000002


In [260]:
w1 = w1novo
w2 = w2novo
w3 = w3novo
w4 = w4novo
print(w1)
print(w2)
print(w3)
print(w4)

0.920264081169131
1.0
1.0
1.2240000000000002
